name=vovagorodok_ArduinoBleSerial
version=0.0.4
author=vovagorodok
maintainer=vovagorodok <vovagorodok2@gmail.com>
sentence=Bluetooth low energy (BLE) library for serial communication.
paragraph=This library supports functionality of serial communication via BLE
url=https://github.com/vovagorodok/ArduinoBleSerial
category=Communication
architectures=esp32,samd,megaavr,mbed,apollo3,mbed_nano,mbed_portenta,mbed_nicla
includes=ArduinoBleSerial.h,ArduinoBleSerialMultiservice.h,ArduinoBleSerialCout.h,ArduinoBleSerialPrintf.h
